# This is a basic workflow to help you get started with Actions

name: CI with Github Security and Jira Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dockerfile-config-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Map a step output to a job output
    #outputs:
    #  trivy_results_artf_name: ${{ steps.trivy-results.outputs.data }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Trivy Config scan for Dockerfiles
      - name: Run Trivy - Dockerfile configuration scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'Dockerfile'
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-dockerfile-config.sarif'
      - name: Upload Trivy Image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-dockerfile-config.sarif'
          category: 'config'
      - uses: actions/upload-artifact@v3
        with:
          name: trivy-dockerfile-config-results
          path: trivy-dockerfile-config.sarif
          retention-days: 30    
  image-sca-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Trivy Image SCA scan
      - name: Run Trivy - Image SCA scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'alpine:3.11'
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-image-sca.sarif'
      - name: Upload Trivy Image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-image-sca.sarif'
          category: 'image_sca'
      - uses: actions/upload-artifact@v3
        with:
          name: trivy-image-sca-results
          path: trivy-image-sca.sarif
          retention-days: 30   
      
        
    
    
        
  #jira-reporting:
    # Jira Vuln Management Reporting
    #needs: dockerfile-config-scan
    #uses: breaktoprotect/jira-vuln-mgmt/.github/workflows/reporting-workflow.yaml@main
