name: GitHub Security Alerts to sync with Jira

on:
  #schedule:
  #  - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.Jira-access-token }}
          JIRA_HOST: https://foo.atlassian.net
          JIRA_USER: someuser@reload.dk
          JIRA_PROJECT: ABC
          JIRA_ISSUE_TYPE: Security
          JIRA_WATCHERS: someuser@reload.dk,someotheruser@reload.dk
